name: Publish ttork

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  regenerate:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create a fresh virtual environment and generate formula
      run: |
        python3 -m venv venv
        source venv/bin/activate
        venv/bin/pip install ttork homebrew-pypi-poet
        poet -f ttork > Formula/ttork.rb
        deactivate
        rm -rf venv
    - name: Replace description and test
      run: |
        python3 -c "
        import re
        content = open('Formula/ttork.rb').read()
        content = re.sub(r'desc \"Shiny new formula\"', 'desc \"Multiple-Repository Tilt Orchestration Tool\"', content)
        content = re.sub(
            r'test do.*?end',
            'test do\\n    assert_match \"ttork, version\", shell_output(\"#{bin}/ttork version\")\\n  end',
            content,
            flags=re.DOTALL
        )
        open('Formula/ttork.rb', 'w').write(content)
        "
        cat Formula/ttork.rb
    - name: Commit and push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |-
        git config user.name "SwordOfDamocles"
        git config user.email "awaller@gmail.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Update ttork: ${timestamp}" || exit 0
        git pull --rebase
        git push